server:
  port: 8081

security:
  jwt:
    public-key: classpath:public.txt

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: ${JAWSDB_URL}
  data:
    mongodb:
      uri: ${MONGODB_URI}