server:
  port: 8081
  error:
    include-message: always

security:
  jwt:
    public-key: classpath:public.txt

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: ${JAWSDB_URL}
    hikari:
      minimumIdle: 1
      maximumPoolSize: 3
  data:
    mongodb:
      uri: ${MONGODB_URI}?retryWrites=false